package dominus.framework.binding;


import com.google.protobuf.InvalidProtocolBufferException;
import dominus.framework.binding.bean.EmployeeProtos;
import dominus.framework.junit.DominusJUnit4TestBase;
import org.junit.Test;

import static org.junit.Assert.assertTrue;


public class TestProtobufBinding extends DominusJUnit4TestBase {

    @Test
    public void testSerDes() throws InvalidProtocolBufferException {

        //EE:Builders vs. Messages
        //The message classes generated by the protocol buffer compiler are all immutable.
        // To construct a message, you must first construct a builder, set any fields you want to set to your chosen values, then call the builder's build() method.
        EmployeeProtos.Employee john = EmployeeProtos.Employee.newBuilder().setEmpNo(21086).setBirthDate(System.currentTimeMillis()).
                setFirstName("shawn").setLastName("guo").setGender("M")
                .setHireDate(System.currentTimeMillis()).build();

        //EE:Standard Message Methods
        out.println(john.toString());
        byte[] ser = john.toByteArray();
        out.println(new String(ser));
        EmployeeProtos.Employee des = EmployeeProtos.Employee.parseFrom(ser);
        assertTrue(john.equals(des));

    }

}
